# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.box_version = "20191107.0.0"
  config.vm.box_check_update = false
  config.vm.synced_folder "./codes", "/home/vagrant/codes"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.cpus = 1
    #vb.gui = true
  end

  config.vm.define "DartVM" do |control|
    control.vm.host_name = "DartVM"
    control.vm.network "forwarded_port", guest: 80, host: 8080
    control.vm.network "public_network"
    control.vm.network "private_network", ip: "192.168.56.1"
  end

  config.vm.provision :shell, :path => "./scripts/vagrant-bootstrap.sh"
end
